# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
-  master

pool:
  vmImage: 'ubuntu-latest'

variables:
  param1: $[variables.parameter1]
  param2: $[variables.parameter2]
  pythonVersion: '3.7'
  answer: $[variables.result]

stages:
- stage: SetVariableValue
  jobs:                
     - job:
       steps:
         
         - task: UsePythonVersion@0
           inputs:
             versionSpec: '$(pythonVersion)'
           displayName: 'Use Python $(pythonVersion)'

         - script: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
           displayName: 'Install dependencies'

         - script: |
             pip install requests
             python deleteRepo.py $(param1) $(param2)
           displayName: 'setting_variable_value'
         - bash: |
             result:"45"
             mkdir -p $(Pipeline.Workspace)/variables
             echo "$result" > $(Pipeline.Workspace)/variables/result
         - publish: $(Pipeline.Workspace)/variables
           artifact: variables

- stage: secondstage
  jobs:
  - job: secondjob
    pool:
      vmImage: 'Ubuntu-16.04'
      steps:
          # Download the artifacts
        - download: current
          artifact: variables

          # Read the variable from the file, then expose it in the job
        - bash: |
            result=$(cat $(Pipeline.Workspace)/variables/FOO)
            echo "##vso[task.setvariable variable=result]$result"

          # Just like in the first example, we can expand the variable within Azure Pipelines itself
        - bash: |
            echo "$(result)"

          # Or we can expand it within bash, reading it as environmental variable
        - bash: |
            echo "$result"  
#- stage: FetchVariable
#  jobs:
#  - job: 
#    steps:
#    - task: PythonScript@0
#      inputs:
#        scriptSource: 'filePath'
#        scriptPath: '$(System.DefaultWorkingDirectory).deleteRepo.py'
#        arguments: '3 3'
